/**
 * commit类型
 */
export enum HomeMutationTypes {
  GET_HOME_DATA = 'GET_HOME_DATA',
  CHANGE_HOME_PAGE_DATA_LOAD = 'CHANGE_HOME_PAGE_DATA_LOAD',
  CHANGE_PRODUCT_CATEGORY_LIST = 'CHANGE_PRODUCT_CATEGORY_LIST',
  GET_PRODUCT_LIST = 'GET_PRODUCT_LIST',
  SET_PRODUCT_LIST = 'SET_PRODUCT_LIST',
}
